name: electron

on:
  push:
    branches: [ main ]

permissions:
  contents: write

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: ./frontend/yarn.lock

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn add electron electron-builder --dev

      - name: Build
        run: |
          yarn build
          yarn electron:build

      - name: Cleanup Artifacts for Windows
        if: matrix.os == 'windows-latest'
        run: |
          npx rimraf "./electron/!(*.exe)"

      - name: Cleanup Artifacts for MacOS
        if: matrix.os == 'macos-latest'
        run: |
          npx rimraf "./electron/!(*.dmg)"

      - name: Upload executables for publish
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact-${{ matrix.os }}
          path: ./frontend/electron

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download executables
        uses: actions/download-artifact@v4
        with:
          pattern: my-artifact-*
          merge-multiple: true
          path: dist

      - name: Deploy to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: "./dist/*"
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          prerelease: true
